# Generated by Django 6.0.4 on 2026-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='daily_target_hours',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
