# Generated by Django 6.0.4 on 2026-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employeeprofile_daily_target_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_restriction_enabled', models.BooleanField(default=False, help_text='اگر فعال باشد، فقط آی\u200cپی\u200cهای لیست زیر اجازه دسترسی دارند.', verbose_name='محدودیت IP فعال')),
                ('allowed_ips', models.TextField(blank=True, help_text='هر آی\u200cپی را در یک خط بنویسید. مثال: 185.10.20.30', verbose_name='آی\u200cپی\u200cهای مجاز')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
