# Generated by Django 6.0.4 on 2026-05-04 08:11

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.avatar_upload_path, verbose_name='تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='درباره من'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
