# Generated by Django 6.0.4 on 2026-05-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_employeeprofile_avatar_employeeprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
    ]
